# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # PropertyOwner
  # ---------------------------------------------------------------------------
  - Name: PropertyOwner
    Domain: property-owner.tudelft.org
    Template:
      Count: 1
    Users:
      Count: 1
    # ---------------------------------------------------------------------------
    # OtaA
    # ---------------------------------------------------------------------------
  - Name: OtaA
    Domain: ota-a.tudelft.org
    Template:
      Count: 1
    Users:
      Count: 1
    # ---------------------------------------------------------------------------
    # OtaB
    # ---------------------------------------------------------------------------
  - Name: OtaB
    Domain: ota-b.tudelft.org
    Template:
      Count: 1
    Users:
      Count: 1
