# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  basic:

services:

  ca.ota-b.tudelft.org:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ota-b.tudelft.org
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ota-b.tudelft.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ota_b_sk
      - FABRIC_LOGGING_SPEC=debug
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ota-b.tudelft.org/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ota-b.tudelft.org
    networks:
      - basic

  peer0.ota-b.tudelft.org:
    container_name: peer0.ota-b.tudelft.org
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.ota-b.tudelft.org
      - CORE_PEER_ADDRESS=peer0.ota-b.tudelft.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ota-b.tudelft.org:7051
      - CORE_PEER_LOCALMSPID=OtaBMSP
      # - CORE_PEER_GOSSIP_USELEADERELECTION=false
      # - CORE_PEER_GOSSIP_ORGLEADER=true
    volumes:
        - /var/run/:/host/var/run/
        - ./otaB/crypto-config/peerOrganizations/ota-b.tudelft.org/peers/peer0.ota-b.tudelft.org/msp:/etc/hyperledger/fabric/msp
        - ./otaB/crypto-config/peerOrganizations/ota-b.tudelft.org/peers/peer0.ota-b.tudelft.org/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - basic

  OtaBcli:
    container_name: OtaBcli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=OtaBcli
      - CORE_PEER_ADDRESS=peer0.ota-b.tudelft.org:7051
      - CORE_PEER_LOCALMSPID=OtaBMSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ota-b.tudelft.org/peers/peer0.ota-b.tudelft.org/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ota-b.tudelft.org/peers/peer0.ota-b.tudelft.org/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ota-b.tudelft.org/peers/peer0.ota-b.tudelft.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ota-b.tudelft.org/users/Admin@ota-b.tudelft.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./otaB/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/org1.example.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.ota-b.tudelft.org
    networks:
      - basic
