name: trustchain
channels:
  - javascript
dependencies:
  - python=2.7
  - pip:
    - cryptography
    - libnacl
    - netifaces
    - Twisted
    - pyOpenSSL
    - six
    # test dependencies
    - nose
    - coverage
    - yappi
    - service_identity
