OrdererOrgs:
  - Name: BookingOrderer
    Domain: eitbooking.overbooking.com
    Specs :
      - Hostname: orderer

PeerOrgs:
  - Name: OTA1
    Domain: ota1.eitbooking.overbooking.com
    # Enable Node Organizaztional Units
    EnableNodeOUs: false
    # A template specifies the number of peers to instanciate with the above PeerOrg config settings
    Template:
      Count: 2
    Users:
      Count: 1
