OrdererOrgs:
  - Name: Orderer
    Domain: overbooking.com
    Specs :
      - Hostname: orderer

PeerOrgs:
  - Name: Booking
    Domain: booking.overbooking.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Airbnb
    Domain: airbnb.overbooking.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
